### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by andresdouglas** [mrkschan/cuttle#16]
It seems like it segfaulted with the following conf file

```
Main: Forwarding request to https://name.myshopify.com:443/admin/shop.json
Segmentation fault (core dumped)
root@:/var/cuttle# cat cuttle.yml
addr: :3128
cacert: './cacert.pem'
cakey: './privkey.pem'
zones:
  - host: "*.myshopify.com"
    shared: false
    control: rps
    rate: 2
  - host: "*"
    shared: true
    control: noop
```

**Comment by andresdouglas** [comment]
OK, it seems like the segfault happens somewhat randomly. the following also caused it to happen. Ran it again and it's working, but segfaults once in a while.

```
# /var/cuttle/bin/cuttle -f /var/cuttle/cuttle.yml
INFO[2016-06-10T15:10:27-04:00] Listening on :3128
INFO[2016-06-10T15:10:32-04:00] Main: Forwarding request to https://domain-staging.myshopify.com:443/admin/products/count.json
Segmentation fault (core dumped)
# cat /var/cuttle/cuttle.yml
addr: :3128
cacert: '/var/cuttle/cacert.pem'
cakey: '/var/cuttle/privkey.pem'
zones:
  - host: "*.myshopify.com"
    shared: false
    control: rps
    rate: 2
```

**Comment by mrkschan** [comment]
@andresdouglas which golang version do you use to compile `cuttle`?

**Comment by andresdouglas** [comment]
```
# go version
go version xgcc (Ubuntu 4.9.3-0ubuntu4) 4.9.3 linux/amd64
```

**Comment by mrkschan** [comment]
@andresdouglas are you using go compiler from golang.org?

My version string looks totally different.

```
go version
go version go1.6.2 linux/amd64
```

I didn't know there is a v4.9.3...

**Comment by andresdouglas** [comment]
OK, did some updating of packages and re-installing of go. Now on 

```
# go version
go version go1.2.1 linux/amd64
```

It seems like it's still a bit wonky. The service seems to continue to run, but on the client side I'm getting a 

`<urlopen error [Errno 54] Connection reset by peer>`

In /var/log/cuttle.err I only get info logs like:

```
time="2016-06-09T16:43:30-04:00" level=info msg="Listening on :3128"
time="2016-06-09T16:44:32-04:00" level=info msg="Main: Forwarding request to https://[...]-staging.myshopify.com:443/admin/shop.json"
time="2016-06-09T16:45:14-04:00" level=info msg="Listening on :3128"
time="2016-06-09T16:45:43-04:00" level=info msg="Main: Forwarding request to https://[...]-staging.myshopify.com:443/admin/shop.json"
```

Should it work with go1.2.1 or do I need to update to go1.6?

Thanks!

**Comment by andresdouglas** [comment]
Just installed go 1.6. I  re-compiled cuttle with go 1.6. Should running the new ./bin/cuttle be sufficient or do I also have to add the 1.6 go binary to the path when running it?

**Comment by andresdouglas** [comment]
Update: no longer segfaults after compiling with 1.6 but after a few Tens of API calls routed through it, it returns a Bad Status Line "" (error in Django)

**Comment by andresdouglas** [comment]
Found something rather interesting when running the proxy manually (only way it seems to print full logging). Seems like a bunch of people - and by this I mean thousands of requests per minute - found and have been using the proxy!

![screen shot 2016-06-21 at 5 30 50 pm](https://cloud.githubusercontent.com/assets/72381/16258152/4e16bc94-3811-11e6-9854-579afbf7fcf0.png)

This is what my cuttle.yml file looks like atm:

```
# cat cuttle.yml
addr: :3128
cacert: '/var/cuttle/cacert.pem'
cakey: '/var/cuttle/privkey.pem'
zones:
  - host: "*.myshopify.com"
    shared: false
    control: rps
    rate: 2
  - host: "*"  # Apply to requests forwarded to all domains.
    shared: true  # The rate limit is shared by all domains.
    control: rps  # Use request-per-second rate limit control.
    rate: 2  # At most 2 requests per second in the entire zone.
```

Is there a way to limit who can route requests through the proxy  (whitelisting?), or limit requests to be routed to the shopify domain only?

I tried setting the rate:0 for the wildcard, but get:

```
# ./bin/cuttle -f cuttle.yml
INFO[2016-06-22T03:39:17-04:00] Listening on :3128
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x5575d8]

goroutine 8 [running]:
panic(0x7bc3e0, 0xc8200100e0)
    /usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/mrkschan/cuttle/cuttle.(*RPSControl).Start.func1(0xc82010edb0)
    /var/cuttle/src/github.com/mrkschan/cuttle/cuttle/limitcontrol.go:71 +0x908
created by github.com/mrkschan/cuttle/cuttle.(*RPSControl).Start
    /var/cuttle/src/github.com/mrkschan/cuttle/cuttle/limitcontrol.go:88 +0x35
```
